name: project-workflow
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get Docker Version
        id: data
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/project3site

      - name: build and push docker
        uses: docker/build-push-action@v5
        with:
          context: .
	  file: /web-content/Dockerfile
          push: true
          tags: ${{ steps.data.outputs.tags }}
